import type { Category } from '@/lib/types/category'

export const categories: Category[] = [
  {
    id: 'architecture',
    name: 'Architecture',
    slug: 'architecture',
    projectSlugs: [
      'territory-part-1',
      'territory-part-2',
      'territory-part-3',
      'iit-representation',
      'art-representation',
      'curve-transformations',
      'bread-drafting',
      'tech-fishery-terminal-si',
      'tech-zen-garden',
      'deceptions-of-reflections',
      'vestiges-in-vapor',
    ],
  },
  {
    id: 'graphic-design',
    name: 'Graphic Design',
    slug: 'graphic-design',
    projectSlugs: [
      'orbit-bleed-poster',
      'need-for-bees-poster',
      'receipt-poster',
      'receipt-album-cover',
      'receipt-extra',
      'territory-part-1-gd',
      'territory-part-2-gd',
      'territory-part-3-gd',
    ],
  },
  {
    id: 'artwork',
    name: 'Art Work',
    slug: 'artwork',
    projectSlugs: [
      'a-road-home-charcoal',
      'an-older-touch-graphite',
      'close-up-scratch-board',
      'eli-c-scratch-board',
      'erase-oil-pastel',
      'graphite',
      'lock-in-pen-drawing',
      'met-scratch-board',
      'print',
      'reflections-graphite-drawing',
      'rooted-pen',
      'sketchbook-1',
      'sketchbook-2',
      'sketchbook-3',
      'sketchbook-4',
      'sketchbook-5',
      'storm-charcoal-drawing',
      'wet-water-color-pencil',
    ],
  },
]
