import type { ScrollConfig } from '@/lib/types/scroll'

const baseReveal = {
  distance: 50,
  opacity: [0, 1] as [number, number],
  scale: [0.95, 1] as [number, number],
  duration: 600,
  stagger: 50,
}

export const scroll: ScrollConfig = {
  preset: 'noah',
  presets: {
    noah: {
      enabled: true,
      smoothScrolling: true,
      momentum: false,
      wheelNavigation: true,
      bodyOverflow: 'hidden',
      wheelDown: 'expand',
      wheelUp: 'collapse',
      arrowHorizontal: 'rotateTabs',
      arrowVertical: 'categoryNav',
      enterKey: 'expand',
      springNavigation: true,
      reveal: baseReveal,
      snap: { enabled: false },
    },
    minimal: {
      enabled: true,
      smoothScrolling: false,
      momentum: false,
      wheelNavigation: false,
      bodyOverflow: 'auto',
      wheelDown: 'none',
      wheelUp: 'none',
      arrowHorizontal: 'none',
      arrowVertical: 'none',
      enterKey: 'none',
      springNavigation: false,
      reveal: {
        distance: 24,
        opacity: [0, 1],
        scale: [1, 1],
        duration: 300,
        stagger: 0,
      },
      snap: { enabled: false },
    },
    parallax: {
      enabled: true,
      smoothScrolling: true,
      momentum: false,
      wheelNavigation: false,
      bodyOverflow: 'hidden',
      wheelDown: 'none',
      wheelUp: 'none',
      arrowHorizontal: 'rotateTabs',
      arrowVertical: 'none',
      enterKey: 'none',
      springNavigation: true,
      reveal: {
        distance: 80,
        opacity: [0, 1],
        scale: [0.9, 1],
        duration: 800,
        stagger: 80,
      },
      snap: { enabled: false },
    },
    snap: {
      enabled: true,
      smoothScrolling: true,
      momentum: false,
      wheelNavigation: true,
      bodyOverflow: 'hidden',
      wheelDown: 'rotateNext',
      wheelUp: 'rotatePrev',
      arrowHorizontal: 'rotateTabs',
      arrowVertical: 'none',
      enterKey: 'expand',
      springNavigation: true,
      reveal: {
        distance: 40,
        opacity: [0, 1],
        scale: [1, 1],
        duration: 400,
        stagger: 0,
      },
      snap: { enabled: true },
    },
    cinematic: {
      enabled: true,
      smoothScrolling: true,
      momentum: true,
      wheelNavigation: false,
      bodyOverflow: 'hidden',
      wheelDown: 'none',
      wheelUp: 'none',
      arrowHorizontal: 'rotateTabs',
      arrowVertical: 'none',
      enterKey: 'none',
      springNavigation: true,
      reveal: {
        distance: 100,
        opacity: [0, 1],
        scale: [0.85, 1],
        duration: 1000,
        stagger: 120,
      },
      snap: { enabled: false },
    },
  },
}
